application: tf2statscolletor
version: 3
runtime: python27
api_version: 1
threadsafe: yes


libraries:
- name: webob
  version: "1.1.1"
- name: lxml
  version: "latest"
- name: setuptools
  version: "latest"
- name: django
  version: "1.2"

handlers:
- url: /static
  static_dir: static
  
- url: .*
  script: main.app
